### PR TITLE
chore(dx-react-chart-docs): update the Material UI link

### PR DESCRIPTION
**Pull request by oliviertassinari**

### CODE REVIEW

**Comment by MaximKudriavtsev** [comment]
@oliviertassinari, do you want to update the same code in the `dx-react-grid` package?

**Comment by oliviertassinari** [comment]
What do you mean?

**Comment by MaximKudriavtsev** [comment]
I mean your last commit `Material-UI is the official name`.

**Comment by oliviertassinari** [comment]
Yes, we would need to go through all the documentation and replace all the occurrences. I haven't done it, just replaced the one I have seen in this file.

**Pull request merged**
