### PR TITLE
perf(react-grid): optimize render using React.memo

### PR DESCRIPTION
**Pull request by LazyLahtak**
Performance increase is about 10%.

### CODE REVIEW

**Comment by churkin** [comment]
What about scheduler?

**Comment by AryamnovEugeniy** [comment]
> What about scheduler?

We will deal with this in the iteration

**Comment by MaximKudriavtsev** [comment]
Should we change all our `PureComponents` without state to `React.memo`?

**Comment by LazyLahtak** [comment]
> Should we change all our `PureComponents` without state to `React.memo`?

It makes sense if we have many same PureComponent in app.

**Pull request merged**
